### ISSUE TITLE
Sense wall fails due to loot actor not having traits

### ISSUE THREAD

**Issue by mcdaddytalk** [JDCalvert/FVTT-Sense-Walls#8]
`function updateVisionLevel(token) {
      let actor = token.actor;
      if (!actor) {
          return;
      }
      console.log(actor);
      let senses = actor.system.traits.senses; // <-- errors here`

Error on line 49 as loot actors do not have `system.traits`

`function updateVisionLevel(token) {
      let actor = token.actor;
      if (!actor || actor.type == 'loot') {
          return;
      }
      console.log(actor);
      let senses = actor.system.traits.senses;`

corrected but I haven't looked to see if anything else if affected

**Comment by JDCalvert** [comment]
Fixed in release 2.0.1, thanks for the report!
